group:
  - files:
      - source: jeykll/devcontainer.json
        dest: .devcontainer/devcontainer.json
      - source: jeykll/Dockerfile
        dest: .devcontainer/Dockerfile
      - source: jeykll/dependabot.yml
        dest: .github/dependabot.yml
      - source: jeykll/.gitignore
        dest: .gitignore
    repos: |
      RamVasuthevan/Personal-Website
      RamVasuthevan/ModernSlaveryStatements
      RamVasuthevan/TaxStrategyStatement
      RamVasuthevan/BestOfUnsplash
  - files:
    - source: new_branch/new_branch.sh
      dest: .devcontainer/new_branch.sh
    repos: |
      RamVasuthevan/Personal-Website
      RamVasuthevan/Shared
  - files:
    - source: python/devcontainer.json
      dest: .devcontainer/devcontainer.json
    repos: |
      RamVasuthevan/savepagenow_client
      RamVasuthevan/whois-server-list
